# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 19:19
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0010_variant_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compare_at_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('p', 'pending'), ('e', 'error'), ('c', 'completed')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='change',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='schedule.Schedule'),
        ),
        migrations.AddField(
            model_name='change',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Variant'),
        ),
    ]
