# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20161022_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('manual', 'manual'), ('storewide', 'storewide discount'), ('collection', 'collection discount')], default='manual', max_length=25),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('e', 'error'), ('c', 'completed')], default='p', max_length=2),
        ),
    ]
