# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20161022_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='theme',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('manual', 'manual'), ('storewide', 'storewide discount'), ('collection', 'collection discount'), ('restore', 'restore')], default='manual', max_length=25),
        ),
    ]
