# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20161024_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='coupons',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
