# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_auto_20161031_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='exclude_promotion',
            field=models.BooleanField(default=False),
        ),
    ]
