# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('contact_person', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', localflavor.us.models.PhoneNumberField()),
            ],
        ),
    ]
