# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20160819_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=localflavor.us.models.PhoneNumberField(blank=True, null=True),
        ),
    ]
