# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0003_auto_20160819_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('vendor_title', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(max_length=50)),
                ('shopify_id', models.BigIntegerField(blank=True, null=True)),
                ('published_scope', models.CharField(default='global', max_length=250)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.Vendor')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
