# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160818_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='template_suffix',
        ),
        migrations.AddField(
            model_name='product',
            name='shopify_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.CharField(max_length=255),
        ),
    ]
