# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20160819_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shopify_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
