# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20161021_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='description',
        ),
        migrations.AlterField(
            model_name='producttype',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
