# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 19:18
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_variant_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
