# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20161022_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='option2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='option3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
