# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20161022_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
