# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20161027_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['product__title', 'position']},
        ),
    ]
