# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-31 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20161028_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
