# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_gmc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='mattress_pieces',
            field=models.IntegerField(default=0),
        ),
    ]
